sudo: false

dist: xenial

language: rust

rust:
  - nightly

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

os:
  - linux
  - osx

env:
  matrix:
    - ARCH="x86_64" SRC="all"
    - ARCH="aarch64" SRC="all"
    - ARCH="riscv32" SRC="all"
    - ARCH="riscv64" SRC="all"
    - ARCH="mipsel" SRC="all"

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
    brew install isl;
    fi
  - if [ 1 ]; then
    [ $ARCH = riscv32 ] && export FILE="riscv32-linux-musl-cross";
    [ $ARCH = riscv64 ] && export FILE="riscv64-linux-musl-cross";
    [ $ARCH = mipsel  ] && export FILE="mipsel-linux-musln32-cross";
    [ $ARCH = aarch64 ] && export FILE="aarch64-linux-musl-cross";
    [ $ARCH = x86_64  ] && export FILE="x86_64-linux-musl-cross";
    if [ $TRAVIS_OS_NAME = linux ]; then
      wget https://musl.cc/$FILE.tgz;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      wget https://mac.musl.cc/$FILE.tgz;
    fi;
    tar -xf $FILE.tgz;
    export PATH=$PATH:$PWD/$FILE/bin;
    fi


before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-xbuild || cargo install cargo-xbuild)

script:
  - make $SRC arch=$ARCH
