sudo: false

dist: bionic

language: rust

rust:
  - nightly-2019-07-15

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

os:
  - linux
  - osx

env:
  matrix:
    - ARCH="x86_64"
    - ARCH="aarch64"
    - ARCH="riscv32"
    - ARCH="riscv64"
    - ARCH="mipsel"

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
    brew install isl;
    fi
  - if [ 1 ]; then
    [ $ARCH = riscv32 ] && export FILE="riscv32-linux-musl-cross";
    [ $ARCH = riscv64 ] && export FILE="riscv64-linux-musl-cross";
    [ $ARCH = mipsel  ] && export FILE="mipsel-linux-musln32-cross";
    [ $ARCH = aarch64 ] && export FILE="aarch64-linux-musl-cross";
    [ $ARCH = x86_64  ] && export FILE="x86_64-linux-musl-cross";
    [ $TRAVIS_OS_NAME = linux ] && export URL="https://musl.cc/$FILE.tgz";
    [ $TRAVIS_OS_NAME = osx   ] && export URL="https://mac.musl.cc/$FILE.tgz";
    [ $TRAVIS_OS_NAME = linux ] && [ $ARCH = riscv32 ] && export URL="https://more.musl.cc/8/x86_64-linux-musl/$FILE.tgz";
    [ $TRAVIS_OS_NAME = osx   ] && [ $ARCH = riscv32 ] && export URL="https://lisa.musl.cc/9.1.0/$FILE.tgz";
    wget $URL;
    tar -xf $FILE.tgz;
    export PATH=$PATH:$PWD/$FILE/bin;
    fi


before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-xbuild || cargo install cargo-xbuild)

script:
  - make tar arch=$ARCH mode=release

deploy:
  provider: releases
  api_key:
    secure: nAnbGCNxvAIBGwIIzzxBdtIKcPJoSZEpJucCXSf1z55CWeODdkALGT4w5tcVRWIM0B/U/x0aC90UvxpLNmPcnhKU6G5Ovm7Y/ygrtjW2AuPgTOorY5KLc6sOGMma6XYcUl9zp3A5QJyQ919myu0+PEhLKv2rOwkxpdHeUqQY3okT7p6VOqtoMCiF8flxo79coTXFM+imEWyuy+CJ/l+34RZhhMjljJh6LTJ+6WATZCD849Jikt5w/vyX3YohuVxS5teLMdy/MwomAWVfRCC0UELHngMwNQic5xTf+l3lNxRB8uK/JJ6VLtiZVxSYXcZhBx26aL0mBaQvto0qyN6g8PApzFII7QvGz+bnUnUHlBgWM9/GTJHsRqS+s4Vw8albAJD0DQz/EtaICdsicGjXgJitcKE5WMY0ttuCMEV0VIxpFTf9bpN6hJQezNolw0iVdgMNjgPeHcEe/PoH59kraS9pz4vpelaPi+Fwf9YINA/Dgvo+gAjsikc1UTPg7tnRevc2b05mHGcLDTTYJ9ic4cjihZaJfxCreIHK9XwxViLE0PoKhtjV930I4rgDWu6A4By/E0m71B7BlOOWdsckLZInQ14U4D4T//F123X3zSDWqtpReqIrFLRzQGrv8/abZYbDnOstWQARJlknPjVdkCBTJ5mIuRgXa4z59PbvYP8=
  file: build/$ARCH.tar.gz
  skip_cleanup: true
  on:
    repo: rcore-os/rcore-user
    tags: true
